Repository ItsKinggpinn/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#4 solved the problem of the quiz.py file with the additional answer.txt…
  Quiz.py
  python/Quiz.py
  python/answers.txt
  python/questions.txt
Labels: help wanted, Hacktoberfest, Hacktoberfest-2022

#10 added the hand cricket game using python programming language
  handCricket.py
Labels: documentation, help wanted, Hacktoberfest, Hacktoberfest-2022

#21 Create a GUI for the main page of the website.
  GUI/Readme
  GUI/bg.jpg
  GUI/index.html
  GUI/iocn-1.png
  GUI/iocn-2.png
  GUI/iocn-3.png
  GUI/sh.png
  GUI/style.css
Labels: good first issue, Hacktoberfest, Hacktoberfest-2022

#22 Pull Request for Matrix Multiplication
  main.c
Labels: good first issue, Hacktoberfest, Hacktoberfest-2022

#24 2nd commit
  stopwatch/index.html
  stopwatch/readme.md
  stopwatch/stopwatch.js
  stopwatch/style.css
Labels: help wanted, Hacktoberfest, Hacktoberfest-2022

#29 1st commit
  Bubble sorting and then Binary Searching with Array
Labels: good first issue, Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#36 committed Number Pattern
  Number_Pattern
Labels: good first issue, Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#37 Spy and Duck number program, 1 commit ahead .
  Untitled-2.c
Labels: good first issue, Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#40 Double Ended Linked List committed
  Double_linked_list.cpp
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#41 Infix to Postfix Conversion
  Infix to Prefix Conversion [Hacktober-2022].pptx
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#43 Merging of two different Linked Lists Committed
  Merge_2_linked_list.cpp
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#45 Fibonacci commit
  Fibonacci Check [Hacktober-22].c
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#47 I added the dataploting part (Question Solved)
  dataplot.py
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted

#50 small_large problem solved
  small_large.py
Labels: Hacktoberfest, Hacktoberfest-2022, Hacktoberfest-Accepted
